# RT-Thread building script for component
Import('RTT_ROOT')

from building import *

cwd = GetCurrentDir()
group = []
if GetDepend('SOC_SERIES_MA35D1'):
	src = Glob('*.c') + Glob('*.cpp')
	CPPPATH = [cwd]
	group = DefineGroup('nu_pkgs_nuwriter', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
